economy:
  enabled: true
  prefix: "&a$"

# Plugin messages.
messages:
  not-enough-money: "&cYou do not have enough money to do this."
  reload-success: "&aConfiguration reloaded!"
  action-create: "&aAction sign successfully created!"
  action-delete: "&cAction sign successfully removed!"
  sneak-required: "&cYou need to sneak to do this."
  permission-use: "&cYou do not have permission to do this."
  action-not-found: "&cThe action '<name>' does not exist. Did you mean to use a slash command?"