economy:
  enabled: true
  prefix: "&a$"

# Plugin messages.
messages:
  sign-create: "&aAction Sign successfully created!"
  sign-delete: "&cAction Sign successfully removed!"
  sign-edit: "&eAction Sign successfully edited!"
  sneak-required: "&cYou need to sneak to do this."
  permission-use: "&cYou do not have permission to do this."

  not-enough-money: "&cYou do not have enough money to do this."
  action-not-found: "&cThe action '<name>' does not exist. Did you mean to use a slash command?"
  reload-success: "&aConfiguration reloaded!"
