name: SimpleActionSigns
main: me.rarehyperion.sas.SAS
version: '0.1.0'
api-version: '1.13'
authors: [RareHyperIon]
load: STARTUP

commands:
  sas:
    description: "Reload the plugins configuration."

permissions:
  sas.use:
    description: "Allows clicking and executing on action signs."
    default: op
  sas.create:
    description: "Allows creating command signs."
    default: op