name: SimpleActionSigns
main: me.rarehyperion.sas.SAS
authors: [RareHyperIon]
website: https://github.com/RareHyperIonYT/Simple-Action-Signs
version: '0.1.2'
api-version: '1.13'
load: STARTUP

soft-depend: [Vault]

commands:
  sas:
    description: "Reload the plugins configuration."
    permission: sas.reload
    usage: /sas reload

permissions:
  sas.use:
    description: "Allows clicking and executing on action signs."
    default: op
  sas.admin:
    description: "Allows creating, editing, and destroying action signs."
    default: op